In [35]:
# let's try to create a sudoku grid and a repository of suitable sets
import numpy as np
number_list = [1,2,3,4,5,6,7,8,9]
cell = np.array(number_list).reshape(3,3)
cell

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# we have one cell. lets try to make a board
board = np.resize(cell,(3,3,3,3))
board, type(board)

(array([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],
 
 
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],
 
 
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]]),
 numpy.ndarray)

In [50]:
# That doesn't look aethetically pleasing, but we can worry about that later.

# Let's see if we can call a sudoku 'column'. It should come out as '1,4,7,1,4,7,1,4,7'
column_test = board[:,0,:,0]
column_test

array([[1, 4, 7],
       [1, 4, 7],
       [1, 4, 7]])

In [55]:
# It doesn't have quite the right format, so let's try to break it down into just a simple list
import itertools
simple_list = list(itertools.chain(*column_test))
simple_list     


[1, 4, 7, 1, 4, 7, 1, 4, 7]

In [57]:
# If we want the program to be functional, it will have to loop over all the rows and columns. Let's try a for loop
def column_check():
    column_set = []
    for x in range(3):
        for y in range(3):
            column = list(itertools.chain(*board[:,x,:,y]))
            column_set.append(column)
    return column_set
    
column_check()

[[1, 4, 7, 1, 4, 7, 1, 4, 7],
 [2, 5, 8, 2, 5, 8, 2, 5, 8],
 [3, 6, 9, 3, 6, 9, 3, 6, 9],
 [1, 4, 7, 1, 4, 7, 1, 4, 7],
 [2, 5, 8, 2, 5, 8, 2, 5, 8],
 [3, 6, 9, 3, 6, 9, 3, 6, 9],
 [1, 4, 7, 1, 4, 7, 1, 4, 7],
 [2, 5, 8, 2, 5, 8, 2, 5, 8],
 [3, 6, 9, 3, 6, 9, 3, 6, 9]]

In [59]:
# That seems to work perfectly. Lets try to make a row function check.
def row_check():
    row_set = []
    for x in range(3):
        for y in range(3):
            row = list(itertools.chain(*board[x,:,y,:]))
            row_set.append(row)
    return row_set
# if this works it will return [1,2,3,1,2,3,1,2,3] in the first row
row_check()

[[1, 2, 3, 1, 2, 3, 1, 2, 3],
 [4, 5, 6, 4, 5, 6, 4, 5, 6],
 [7, 8, 9, 7, 8, 9, 7, 8, 9],
 [1, 2, 3, 1, 2, 3, 1, 2, 3],
 [4, 5, 6, 4, 5, 6, 4, 5, 6],
 [7, 8, 9, 7, 8, 9, 7, 8, 9],
 [1, 2, 3, 1, 2, 3, 1, 2, 3],
 [4, 5, 6, 4, 5, 6, 4, 5, 6],
 [7, 8, 9, 7, 8, 9, 7, 8, 9]]

That's great! Good progress.

But these don't meet the constraints of sudoku. We need two things. A function that verifies the integrity of each row and column, and Random iterations of the sudoku board that have been verified.



In [68]:
def verify_board(board):
    row_set = []
    column_set = []
    verified = True 
    for x in range(3):
        for y in range(3):
            column = list(itertools.chain(*board[:,x,:,y]))
            row = list(itertools.chain(*board[x,:,y,:]))
            if len(list(set(column))) and len(list(set(row))) != 9:
                print('failure!')
                verified = False
                break
            else:
                print(row,column)
                row_set.append(row)
                column_set.append(column)
    if verified == True:
        return board
verify_board(board)

failure!
failure!
failure!


Ok, well this may work. However flagging a clearly failing board does not mean it will be successful in verifying a correct one 

We can run this function anytime we randomize the board so lets try to make a function for that.

In [80]:
#each cell is correct, so the cell doesn't need to be changed. Let's create a board of repeatedly randomized cells.

np.random.shuffle(number_list)
number_list

[1, 6, 7, 9, 4, 8, 2, 3, 5]

In [84]:
# We will try to create 9 shuffled number_lists and reshape them into a board
cells = []
for i in range(9):
    np.random.shuffle(number_list)
    cells.append(number_list)
board = np.array(cells).reshape(3,3,3,3)
# If this works, it should return 1-9
board[0,0,:,:]

array([[3, 2, 8],
       [7, 6, 4],
       [5, 9, 1]])

Whew! nice! Now we can create a suitable function that serves and verifies a board.
